### ISSUE TITLE
Paginated Search

### ISSUE THREAD

**Issue by rkulla** [lionelbarrow/braintree-go#112]
While using braintree-go at Daily Burn a while back, we noticed that the transaction search would only return the first 50 results or so, so we added paginated search results to the library. 

Haven't been able to find the time to clean up our code and submit a proper PR but here is an example of what we did if someone wants to use as a reference to implement this if there's no existing way to do it https://github.com/dailyburn/braintree-go/commit/d44aa131caad6055c0e4aac2f3a24450aa818c63

**Comment by ilayaraja89** [comment]
Does the same applicable for Customers search ?

**Comment by leighmcculloch** [comment]
@ilayaraja89 I think so yes, although that could be a separate piece of work. Looking at the Braintree Java SDK it looks like each object that can be search with pagination has a "Pager" class.

Examples:
[TransactionPager.java](https://github.com/braintree/braintree_java/blob/master/src/main/java/com/braintreegateway/TransactionPager.java)
[CustomerPager.java](https://github.com/braintree/braintree_java/blob/master/src/main/java/com/braintreegateway/CustomerPager.java)
