### ISSUE TITLE
Add a CHANGELOG before next version

### ISSUE THREAD

**Issue by leighmcculloch** [lionelbarrow/braintree-go#125]
We should add a CHANGELOG to the project that outlines significant changes and new features between releases. As this package is still pre-v1 there may be small breaking changes in the exported api and this will be one place we can also highlight them between pre-v1 versions, and between major versions when we have them.

Suggested by @jszwedko in comments on #120.

**Comment by jszwedko** [comment]
Took a stab at this in #126

**Comment by jszwedko** [comment]
Apologies, in hindsight creating this issue first would have been better so that I could make sure I wasn't stepping on toes.
