### ISSUE TITLE
Specify default http.Client timeout

### ISSUE THREAD

**Issue by dannyvankooten** [lionelbarrow/braintree-go#133]
Hey,

While right now we can use `NewWithHttpClient` to pass in our own HTTP client, would it make sense to choose a sensible default for the `Timeout` field instead of using `net/http`'s default client (which has no timeout)?

I went through our codebase after reading [this post](https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779), so just dropping notes where I can. 

Thanks for the renewed attention for this package by the way. Using it in production and it's been great! Any chance Braintree will "officially" support this one?

**Comment by leighmcculloch** [comment]
@dannyvankooten: Thanks that's a good catch. I think it makes sense for us to do as you say and provide a default client that isn't `net/http`s. Taking a look at the Braintree official SDKs for [Java](https://github.com/braintree/braintree_java/blob/1ea23ca33e9290ffb79ce458b0978e94737981e1/src/main/java/com/braintreegateway/Configuration.java#L139), [Ruby](https://github.com/braintree/braintree_ruby/blob/4247c3a9ead174815879c1062c9169c589aec24c/lib/braintree/configuration.rb#L92), and [Node](https://github.com/braintree/braintree_node/blob/aec33195246d2a09a0b7a0efcf11ab9eaf01819b/lib/braintree/config.js#L7) they all set the timeout to 60 seconds by default.

**Comment by leighmcculloch** [comment]
@dannyvankooten: See #134.

**Comment by dannyvankooten** [comment]
Whoa, that was fast. Looks good to me!

On April 23, 2017 7:46:27 AM GMT+02:00, Leigh McCulloch <notifications@github.com> wrote:
>@dannyvankooten: See #134.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/lionelbarrow/braintree-go/issues/133#issuecomment-296421382

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by leighmcculloch** [comment]
Change has been made to set a 60s timeout by default which is consistent with the official SDKs. It'll be included in the next release, v0.12.0.
