### ISSUE TITLE
Make newHmacer Exported

### ISSUE THREAD

**Issue by RichardKnop** [lionelbarrow/braintree-go#138]
Correct me if I am wrong but if I want to create an API endpoint in Golang to parse Braintree webhooks, I will need to build HMAC signature in order to parse the webhook data.

So I would need to do something alongside these lines:

```go
package api

import (
	"encoding/base64"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

// BraintreeWebhook - GET /api/v1/braintree-webhook/
func BraintreeWebhook(w http.ResponseWriter, r *http.Request) {
	// Request body cannot be nil
	if r.Body == nil {
		http.Error(w, "Request body cannot be nil", http.StatusBadRequest)
		return
	}

	// Read the request body
	payload, err := ioutil.ReadAll(r.Body)
	if err != nil {
		http.Error(w, "Error reading request body", http.StatusBadRequest)
		return
	}

	webhookGateway := testGateway.WebhookNotification()
	hmacer := newHmacer("my_public_key", "my_private_key")

	hmacedPayload, err := hmacer.hmac(base64.StdEncoding.EncodeToString(payload))
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	signature := fmt.Sprintf("%s|%s", hmacer.publicKey, hmacedPayload)

	notification, err := webhookGateway.Parse(signature, payload)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	log.Print("Printing parsed notification: ")
	log.Printf("%v", notification)

	// business logic ...

	w.WriteHeader(http.StatusOK)
	fmt.Fprint(w, "Notification accepted")
}
```

The problem is the `newHmacer` function is not exported.

It would be to export this functionality so it can be imported by projects as currently I have to copy paste it.

**Comment by RichardKnop** [comment]
Ignore this. I think I know what I was doing wrong.

**Comment by leighmcculloch** [comment]
@RichardKnop: In the request body there will be two form parameters, `bt_payload` and `bt_signature`. If you use `webhookGateway.Parse(r.FormValue("bt_signature"), r.FormValue("bt_payload"))` that function will use the hmacer to verify the signature and will return a `*WebhookNotification`.

We could probably add a helper `ParseRequest` method that took a `http.Request` and unpacked the two. It would make using this more straightforward I think. Would that have helped reduce the confusion?
