### ISSUE TITLE
How To Get Signature From Request

### ISSUE THREAD

**Issue by RichardKnop** [lionelbarrow/braintree-go#139]
Hello, 

How can I get signature from `*http.Request` object in my handler where I want to parse a webhook notification like this:

```go
payload, err := ioutil.ReadAll(r.Body)
if err != nil {
	http.Error(w, "Error reading request body", http.StatusBadRequest)
	return
}

bt.WebhookNotification().Parse(signature, string(payload))
```

I assume `payload` is just the content of `HTTP POST` data but where is `signature`? In one of the headers?

**Comment by leighmcculloch** [comment]
In the request body there will be two form parameters, bt_payload and bt_signature. If you use webhookGateway.Parse(r.FormValue("bt_signature"), r.FormValue("bt_payload")) that function will use the hmacer to verify the signature and will return a *WebhookNotification.

We could probably add a helper ParseRequest method that takes a http.Request and unpacked the two. It would make using this more straightforward I think.

**Comment by RichardKnop** [comment]
@leighmcculloch Oh thanks. This is helpful :)
