### ISSUE TITLE
AVS/CVV/Gateway/Tax Amount/Tax Exempt Transaction Fields

### ISSUE THREAD

**Issue by ccahoon** [lionelbarrow/braintree-go#143]
Hello! Thanks for the great library. It's exciting to see so much great work being done on it!

I've got a branch based on a fairly old revision that implements a couple more transaction fields (and some alternative implementations of great work you've done since then). I haven't updated to the latest revision, but in a few months when I do, I'd be able to submit a pull request, but I wanted to ask first—would you prefer a PR at that point, or just a note that I'd use them if you added them?

**Comment by leighmcculloch** [comment]
@ccahoon: A PR would be fantastic! Feel free to drop a list of requested fields (separate issues for each preferably), but if you open a PR there's a chance that what gets merged will align with your own solution.

**Comment by ccahoon** [comment]
Great! In the process of writing the test, I've discovered (I think) that the sandbox account doesn't have AVS and CVV rules enabled. Do you think it'd be problematic for other tests to turn them on?

**Comment by leighmcculloch** [comment]
@ccahoon: I've add a merchant account to the sandbox account the tests run against that has AVS and CVS turned on. All the rules are turned on just for this merchant account id.

Merchant Account ID: `avs-and-cvs`

Note: `cvs` was supposed to be `cvv` but I made a typo, and can't change it. 😭

**Comment by ccahoon** [comment]
Looks like we've done all of the bits of this issue! Thanks so much for working with me on it.

**Comment by leighmcculloch** [comment]
Thanks for kicking this off and contributing with PRs. It led to some great improvements to the package all round!
