### ISSUE TITLE
Does Transaction.CustomerId exits?

### ISSUE THREAD

**Issue by RichardKnop** [lionelbarrow/braintree-go#150]
I have not being able to see XML tag corresponding to `Transaction.CustomerId` field:

https://github.com/lionelbarrow/braintree-go/blob/master/transaction.go#L13

Is this a mistake or is it returned with XML in some cases?

The way to get customer ID from transaction object is `Transaction.Customer.Id`, because `Transaction.CustomerId` will always be empty.

**Comment by leighmcculloch** [comment]
@RichardKnop: Nice spotting. I ran a few integration tests and I didn't see it come back in the response at all either. I think this is an artifact of when the `Transaction` struct use to be used for the request and the response, but now it's only used for the response. See #151.
