### ISSUE TITLE
support context.Context in all remote APIs

### ISSUE THREAD

**Issue by jmhodges** [lionelbarrow/braintree-go#156]
Passing contexts around for timeouts, cancellation, and other behaviors is now common and well-documented in Go land. It'd be really nice to have support for that in braintree-go. Even Context versions of the methods like how `database/sql` was updated would work.

**Comment by leighmcculloch** [comment]
@jmhodges: Would you like to open a PR adding context to one area of the SDK which could be iterated on, and then we can adapt that pattern to the rest of the library?

**Comment by jmhodges** [comment]
Can do!

**Comment by jmhodges** [comment]
Did the AddonGateway and AddressGateway in https://github.com/lionelbarrow/braintree-go/pull/158
