### ISSUE TITLE
Open REST Api

### ISSUE THREAD

**Issue by cannapages** [lionelbarrow/braintree-go#19]
Do you have documentation on the brain tree rest API. I read an article where they stated they only want to expose client API's and I would like to contribute to this one however without any documentation I am flying blind.

**Comment by jszwedko** [comment]
@cannapages unfortunately the HTTP API isn't documented. The best thing to do is to look at one of the existing client library implementations to see the expected behavior.

**Comment by lionelbarrow** [comment]
Yep, sorry there isn't any public REST API documentation.

**Comment by tejasmanohar** [comment]
Not gonna lie, this kinda sucks. I love Stripe's approach of having both a well-documented REST API and great client libraries- I don't think it has to be one or the other.
