### ISSUE TITLE
Remove flag.Parse() from init() please

### ISSUE THREAD

**Issue by munknex** [lionelbarrow/braintree-go#195]
https://github.com/lionelbarrow/braintree-go/blob/95dec3d454ce596f89da7e18822aa7796c8641e7/test_values.go#L78

It is impossible to use flags in main package because of this.

**Comment by leighmcculloch** [comment]
Whoops, I introduced that in #192 just recently but it was supposed to be inside a `_test.go` file so that it was included in the built package. Will share a fix shortly.

**Comment by leighmcculloch** [comment]
Fixed in #196.
