### ISSUE TITLE
number_of_billing_cycles missing in Modification

### ISSUE THREAD

**Issue by buola** [lionelbarrow/braintree-go#199]
the Modification structure is missing the number_of_billing_cycles field, which makes it impossible to get the default number of cycles of a discount/add-on ID, or the number of cycles of a discount/add-on within a subscription

**Comment by leighmcculloch** [comment]
That shouldn't be too difficult to add. @buola would you be up for adding the field and submitting a PR? This would be a good change for a first contribution.

**Comment by leighmcculloch** [comment]
Added in #200. Will be in next release.
