### ISSUE TITLE
TLS 1.2 as default

### ISSUE THREAD

**Issue by bastiankoetsier** [lionelbarrow/braintree-go#207]
Hey, 

given the fact that Braintree will drop TLS support for [less than 1.2](https://www.braintreepayments.com/blog/updating-your-production-environment-to-support-tlsv1-2), would you accept a PR that sets this as the default minimum TLS version to be used by the actual HTTP client?

**Comment by leighmcculloch** [comment]
👍 we should setup the HTTP Client with the best defaults for sure.

**Comment by leighmcculloch** [comment]
This has been done in #208 and is merged, and will be in `v0.18.0` when it's released.
