### ISSUE TITLE
Credit card token field is not set after transaction

### ISSUE THREAD

**Issue by AnandSundar** [lionelbarrow/braintree-go#216]
Hi,

Thank you for building this go package for braintree.
I may have found a possible issue that I want to bring to your attention.

When I run the code mentioned below, the transaction got approved but the tx.CreditCard.Token (tokenized credit card number) field is not set. Can anyone fix this please?
  
        bt := braintree.New(
		braintree.Sandbox,
		"47sdtstnwjp8xy7k",
		"nxf5g2kx2wgdtrrs",
		"********************************",
	)

	ctx := context.Background()
	tx, err := bt.Transaction().Create(ctx, &braintree.TransactionRequest{
		Type: "sale",
		Amount: braintree.NewDecimal(100, 2), // 100 cents
		CreditCard: &braintree.CreditCard{
			Number:         "4111111111111111",
			ExpirationDate: "05/14",
		},
	})

**Comment by leighmcculloch** [comment]
The `Transaction.CreditCard.Token` field is only set to a value if the credit card has been vaulted, either by storing it as a payment method, or by instructing the API to store the card in the vault while processing the transaction. See the Braintree developer docs [here](https://developers.braintreepayments.com/reference/response/transaction/java#credit_card_details.token).

```go
ctx := context.Background()
tx, _ := gateway.Transaction().Create(ctx, &TransactionRequest{
    Type:   "sale",
    Amount: NewDecimal(100, 2),
    CreditCard: &CreditCard{
        Number:         testCreditCards["visa"].Number,
        ExpirationDate: "05/14",
    },
    Options: &TransactionOptions{
        StoreInVault: true,
    },
})
```
