### ISSUE TITLE
Tokenization of Credit Card without making a sale

### ISSUE THREAD

**Issue by AnandSundar** [lionelbarrow/braintree-go#217]
Hi,

I'm building a software that tokenizes credit card numbers using your Go package and would very much appreciate if you guys can add this following functionality.

I want to get a token (Credit card number that is tokenized) from Braintree without making a sale (i.e) I want Braintree to give me a token back without charging the credit card.

Thanks,

**Comment by leighmcculloch** [comment]
@AnandSundar There's a couple ways you might want to do this with this SDK:

1. Using a Client SDK and this Server SDK

   Normally you'd use the [Braintree Client SDKs](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v2) to pass a card and get back a `nonce`, then use the `nonce` with this SDK's `PaymentMehthodGateway` to vault the nonce, and then you'd get back a `token`. Ref: https://developers.braintreepayments.com/start/overview

   Here's an example in one of the tests:

   https://github.com/lionelbarrow/braintree-go/blob/983e37a22a88f386e2ea93df267c28bf211b133f/payment_method_integration_test.go#L20-L34

2. Using just this Server SDK

   If you just want to use this Server SDK and no Client SDK, you can skip the nonce and use the `CreditCardGateway` to vault a card and you'll get back a `CreditCard` value that has `Token` field.

   Here's an example in one of the tests:

   https://github.com/lionelbarrow/braintree-go/blob/983e37a22a88f386e2ea93df267c28bf211b133f/credit_card_integration_test.go#L21-L38

Note: In both cases you'll need to also create a `Customer` and assign the `PaymentMethod`/`CreditCard` to the `Customer`.

Please reopen the issue if this doesn't resolve your question.
