### ISSUE TITLE
Is there any PayPal example?

### ISSUE THREAD

**Issue by DonMillion** [lionelbarrow/braintree-go#226]
I want to pay with paypal, but I can't find entrance to put my merchantAccountId when I generate the token.
So I try to create transcation or subcription with nonce and put my merchantAccountId in the transcationRequest or subcriptionRequest. It told me that Payment instrument type is not accepted by this merchant account.

PS: I try it in sandbox env

**Comment by leighmcculloch** [comment]
@DonMillion the only example of a PayPal transaction in this SDK are in the integration tests: 

https://github.com/lionelbarrow/braintree-go/blob/e40fff02a52df6c04c87e57673e5dd7f41f3569a/transaction_paypal_details_integration_test.go#L13-L39

The standard Braintree developer docs discuss how to accept PayPal using the iOS, Android or JS SDKs: https://developers.braintreepayments.com/guides/paypal/overview. Once you get a `PaymentMethodNonce` from one of those SDKs you can pass it into the Braintree Go SDK like in the test above.

**Comment by leighmcculloch** [comment]
@DonMillion You may like to contact Braintree's support: https://developers.braintreepayments.com/forms/contact.

**Comment by DonMillion** [comment]
Is works in production env. I am trying to contact Braintree's support for help about sandbox env
