### ISSUE TITLE
Support Dispute object in webhooks

### ISSUE THREAD

**Issue by vania-pooh** [lionelbarrow/braintree-go#228]
1) Need to define respective structs and support unmarshalling of `braintree.WebhookNotification.Subject` to a `Dispute`.
2) Currently no need to implement API handles like [this](https://developers.braintreepayments.com/reference/request/dispute/accept/ruby).

If this feature is OK for you - can send respective PR.

**Comment by leighmcculloch** [comment]
@vania-pooh Indeed, please send a PR and I'll take a look at getting it merged.
