### ISSUE TITLE
Add Go Report Card

### ISSUE THREAD

**Issue by tengis617** [lionelbarrow/braintree-go#230]
This project is great! kudos to the maintainers/contributors!
I wonder if we could add a Go Report Card Badge, and maybe fix some minor stylistic issues (e.g comments for exported methods) to make this library even more awesome?

**Comment by leighmcculloch** [comment]
@tengis617 I think that's a good idea. Adding comments on exported types would improve the godoc for sure. We could start with adding the Go Report Card Badge as you said, then address the other things over time. Are you up for opening a PR to add the badge?

**Comment by tengis617** [comment]
@leighmcculloch awesome! i'll make a PR!

**Comment by leighmcculloch** [comment]
Thanks @tengis617 ! It's merged!
