### ISSUE TITLE
How to get transaction response status

### ISSUE THREAD

**Issue by kinqsley** [lionelbarrow/braintree-go#241]
I have the subscription creation and how can I receive the transaction response code? I want to know the error code and message if the subscription/transaction is failed.

```
subscription, err := bt.Subscription().Create(ctx, &braintree.SubscriptionRequest{
	PlanId: plan,
	PaymentMethodToken: customer.DefaultCreditCard().Token,
})
```

**Comment by leighmcculloch** [comment]
@kinqsley You can use the `Transactions` field on `Subscription` to get the transactions for a subscription. For a new subscription there should just be one.

https://github.com/lionelbarrow/braintree-go/blob/983e37a22a88f386e2ea93df267c28bf211b133f/subscription.go#L49

Ref: https://developers.braintreepayments.com/reference/response/subscription#transactions
