### ISSUE TITLE
Fetch all customers

### ISSUE THREAD

**Issue by vania-pooh** [lionelbarrow/braintree-go#256]
In my code I have a periodic background process that needs to somehow fetch `all` customers via Braintree API and then do some processing for every customer (mainly related to manually handling trial expiration). Right now `CustomerGateway` has `Search(ctx context.Context, query *SearchQuery)` method to get a list of customers.

**My question:** is a single call to this method with an empty search query sufficient to get a list of all customers?

My intuition says - something is missing in the client as I'm seeing `CurrentPageNumber`, `PageSize` and `TotalItems` fields in the `CustomerSearchResult` structure but no way to use these fields. So how would I fetch all the customers? If something is missing I could send respective PR.

**Comment by vania-pooh** [comment]
In Java and Ruby client I'm also seeing methods to fetch all customer IDs and nothing similar in this one.

**Comment by leighmcculloch** [comment]
You're right there is logic missing in the SDK. The SDK only gives you the first page (probably 50) of customers. If you'd like to open a PR adding the logic, follow the patterns in the `TransactionGateway`'s functions: `SearchIDs` and `SearchPage`, where the first function will get you a list of all the IDs for a search result, and the second will then page through the IDs.

Note: The Braintree API only returns a maximum number of results for any search query. For customer that max is 10,000. Ref: https://developers.braintreepayments.com/reference/general/searching/search-results#search-limit

**Comment by vania-pooh** [comment]
@leighmcculloch ok, will send a PR.
