### ISSUE TITLE
Use a "nullable" type for primitive values that may be empty in Braintree responses

### ISSUE THREAD

**Issue by jszwedko** [lionelbarrow/braintree-go#27]
E.g. `Plan.NumberOfBillingCycles` may be empty in the response XML from Braintree, but is otherwise an integer. We currently deserialize to a `string` to avoid this issue.

Possible solutions:
- Create types that can either be an `int` (or `bool`, `float`, etc.) or `nil` and use those (similar to `sql.NullInt`)
- Make use of https://github.com/guregu/null which does this work, but would require us to introduce a third-party dependency and expose that dependency to the end user

**Comment by jszwedko** [comment]
I'm currently leaning towards rolling our own to avoid the dependency.

**Comment by lionelbarrow** [comment]
Done.
