### ISSUE TITLE
Prefix tags with `v` to support gopkg.in?

### ISSUE THREAD

**Issue by jszwedko** [lionelbarrow/braintree-go#29]
If we specify the tags with a leading `v`, people can use this library with http://labix.org/gopkg.in. This might be nice while the API is still stabilizing.

Reference: http://labix.org/gopkg.in#SupportedURLs

**Comment by leighmcculloch** [comment]
Agree this is something we should do and would be consistent with other calls for semver consistency with a prefixed `v` in the go community. e.g. https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by leighmcculloch** [comment]
I just pushed tags for `v0.10.0` and the previous release `v0.9.0` so if people want to use these or newer versions with gopkg.in they can.
