### ISSUE TITLE
404 Error ?

### ISSUE THREAD

**Issue by joaojeronimo** [lionelbarrow/braintree-go#37]
Hey, I just got a 404 error [here](https://github.com/lionelbarrow/braintree-go/blob/master/credit_card_gateway.go#L16) does that mean braintree may have changed it's API and this is now pointing to the wrong place ?

**Comment by joaojeronimo** [comment]
Sorry, my mistake

**Comment by CoreyCole** [comment]
Hey @joaojeronimo, I'm getting the same error when I try to use the transaction example. What did you do to fix it? I feel like I'm missing something.
