### ISSUE TITLE
Refund Capability

### ISSUE THREAD

**Issue by codewitch** [lionelbarrow/braintree-go#39]
Hi there,

I've looked and there doesn't seem to be a Refund capability for settled transactions at the moment. Could you confirm this?

If so, can I put it as a function of TransactionGateway in a pull request? It looks like it should be a POST to "/transactions/#{transaction_id}/refund" with params: transaction => {:amount => amount})

Thanks!
Thomas

**Comment by lionelbarrow** [comment]
Yep, looks like you've got it right in the pull request.

**Comment by lionelbarrow** [comment]
Gonna close this since I've merged https://github.com/lionelbarrow/braintree-go/pull/40 in.
