### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by lionelbarrow** [lionelbarrow/braintree-go#4]
Hey @eaigner, would you find the advanced search functionality described [here](https://www.braintreepayments.com/docs/ruby/transactions/search) or [here](https://www.braintreepayments.com/docs/ruby/subscriptions/search) useful? I was thinking of taking a crack at it this weekend.

**Comment by leighmcculloch** [comment]
I think this was resolved when [search.go](https://github.com/lionelbarrow/braintree-go/blob/9ef9669d52433c62f284b266c2617334c9b1f914/search.go) was added. Please reopen if needed.
