### ISSUE TITLE
Adding payment Methods for a Customer from Nonce

### ISSUE THREAD

**Issue by sadlil** [lionelbarrow/braintree-go#45]
I am trying to use your library for developing an application. On that i am using drop-in UI. that sends payment_method_nonce. I can manage successful transaction using this, But the problem is i can not use this while subscribing a plan. I have customer info coming from another source. So when adding customer i do not have any credit card information. So i need to add payment Method from nonce when user submits the drop-in ui forms.

[On Php](https://developers.braintreepayments.com/javascript+php/guides/payment-methods#create)
[On Java](https://developers.braintreepayments.com/javascript+java/guides/payment-methods#create)

Is there anything for this go lib? if not do you have it in mind to implement in near future?

Thanks for writing this library.

**Comment by sadlil** [comment]
I solved this problem By using this:

fmt.Printf("[DEBUG] Nonce From Html: %s\n", nonce)
	customer, err := bt.Customer().Create(&customerData)
	if(err != nil) {
		fmt.Println("[EROR] Can not create Customer ", err)
		return false
	}
	fmt.Println("[DEBUG] Customer Created Id ", customer.Id)
	card, cardErr := bt.CreditCard().Create(&braintree.CreditCard{
		CustomerId:     customer.Id,
		PaymentMethodNonce: nonce,
		Options: &braintree.CreditCardOptions{
			VerifyCard: true,
		},
	})
	if(cardErr != nil ) {
		fmt.Println("[EROR] Card Creatinon Error ", cardErr)
	}
	fmt.Println("[DEBUG] Customer Credi Card Created Id ", card.CardType)

	sub, subErr := bt.Subscription().Create(&braintree.Subscription{
		PaymentMethodToken: card.Token,
		PlanId:             planId,
		Options: &braintree.SubscriptionOptions{
			ProrateCharges:                       true,
			RevertSubscriptionOnProrationFailure: true,
			StartImmediately:                     true,
		},
	})

**Comment by tsirolnik** [comment]
Saved my day.
On a side note, I suggest adding more examples. Maybe I'll add one when I finish the basics with it.
