### ISSUE TITLE
401 Unauthorised when trying form example

### ISSUE THREAD

**Issue by 17twenty** [lionelbarrow/braintree-go#48]
I'm using your example server.go with form.html and when I feed it my values it gives back an Unauthorised 401 - known issue?

Have I missed a step? I ran go run server.go and hit it at localhost with a demo credit card of:
"4111111111111111"
"05/2010"
"100"

which should succeed. I even hardcoded my merch details into the app for testing and still unauthorised.

**Comment by 17twenty** [comment]
Scratch that - something was wrong with my shell. I'm gonna apologise and slyly blame my El Capitan upgrade :+1:

**Comment by lionelbarrow** [comment]
:
