### ISSUE TITLE
Oauth gateway for partners API

### ISSUE THREAD

**Issue by olivoil** [lionelbarrow/braintree-go#50]
Hi,

I would love to see support for the oauth gateway to enable using the partners API.

The documentation from braintree is [here](https://developers.braintreepayments.com/guides/partner-api/oauth/ruby), and I believe the ruby equivalent is [here](https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/oauth_gateway.rb).

Has anyone started working on it? Is anyone else interested?

**Comment by leighmcculloch** [comment]
#52 was closed without intention to support the oauth gateway, closing this also.
