### ISSUE TITLE
Transaction Currency

### ISSUE THREAD

**Issue by pedromg** [lionelbarrow/braintree-go#54]
We need to use other currencies other than Euro on our system. There seems to be no support for currencies on Transactions implemented, so we added:

```CurrencyIsoCode string `xml:"currency-iso-code,omitempty"` ```

to transaction.go

Yet, when we try to process a transaction:
```
tx, err := bt.Transaction().Create(&braintree.Transaction{
  Type: "sale",
  CurrencyIsoCode: string(b.Currency),
  Amount: braintree.NewDecimal(int64(b.Total*100), 2),
  PaymentMethodToken: cc.Token,
})
```
we get on the response the error:

Forbidden (403)

Does it have to do with the implementation or the account definition ?

**Comment by lionelbarrow** [comment]
Sorry for the confusion -- that's not how Braintree's API works. You don't set the currency directly on an API call. Rather, each of your merchant accounts has a currency associated with it, and you can specify the currency by changing the merchant account. This article has more details: https://articles.braintreepayments.com/get-started/currencies

**Comment by pedromg** [comment]
:+1: yes, thanks, working now
