### ISSUE TITLE
Runnung the tests

### ISSUE THREAD

**Issue by manuelstofer** [lionelbarrow/braintree-go#57]
I did not find out how to create a transaction with the id 'dskdmb' to run the tests successfully.

**Comment by leighmcculloch** [comment]
@manuelstofer: It's not possible to set the id of a transaction. To run all the tests successfully including the integration tests that use the `dskdmb` transaction with your own sandbox account would probably require you to change the transaction id in the test to a transaction id in your own account. Maybe we could make the id an environment variable that can be set..
