### ISSUE TITLE
Recurring billing payment nonce

### ISSUE THREAD

**Issue by mnzt** [lionelbarrow/braintree-go#58]
Following the docs here:
https://developers.braintreepayments.com/guides/recurring-billing/create/ruby

The `Subscription` struct should therefore contain a payment method nonce.

**Comment by mnzt** [comment]
I haven't taken a look at the src for this API yet, so if someone familiar would like to have a shot at this first that'd be ideal. If not, I'll crack it open and see what I can do.

**Comment by mnzt** [comment]
Unless you include a transaction with the nonce under the `Transactions` literal?

**Comment by mnzt** [comment]
Bumpety bump

**Comment by dannyvankooten** [comment]
I think you can already specify the `PaymentMethodToken` on the Subscription struct. The [example here](https://github.com/lionelbarrow/braintree-go/blob/master/examples/subscription/server.go#L84) does it.

However, there doesn't seem to be support for the [Braintree payment method objects](https://developers.braintreepayments.com/guides/payment-methods/ruby) yet. I'm looking into this as we speak as I'm using Braintree for PayPal payments and not using their credit card method at all.

**Comment by leighmcculloch** [comment]
@mnzt @dannyvankooten: You can specify the payment method nonce on the `SubscriptionRequest` when creating the subscription. Note that there is also a `PaymentMethodToken` field, and that won't take a nonce, you need the one named `PaymentMethodNonce`.
