### ISSUE TITLE
Sample Webhook notification

### ISSUE THREAD

**Issue by chambo-e** [lionelbarrow/braintree-go#72]
Hello,
Is there a way to generate a sample webhook notification like in other drivers ?
I can work on a PR if needed.
Thanks

**Comment by leighmcculloch** [comment]
@chambo-e: There isn't one in this package, but did you want to open a PR adding a webhook testing gateway? The java library has one we could use as a base: https://github.com/braintree/braintree_java/blob/master/src/main/java/com/braintreegateway/WebhookTestingGateway.java

**Comment by RichardKnop** [comment]
@chambo-e See my PR: https://github.com/lionelbarrow/braintree-go/pull/142
