### ISSUE TITLE
Device data support

### ISSUE THREAD

**Issue by rzoom** [lionelbarrow/braintree-go#73]
Hi, I love the project and am trying to use full Go for a new site.  According to [this](https://developers.braintreepayments.com/guides/paypal/server-side/ruby#using-device-data), it is recommended to provide device data when using a Vault record initiate a transaction.  I do not see any way to provide this data using the Go lib.  I have already collected the device data, just need a way to provide it to Braintree.

Thanks,
Rob

**Comment by lionelbarrow** [comment]
Hey Rob,

I think this PR will help you out: https://github.com/lionelbarrow/braintree-go/pull/76

Note that device data is only required for transactions using PayPal as a payment method.

**Comment by leighmcculloch** [comment]
Closing this as #76 is merged and the device data can be provided to Braintree by setting it into the `Transaction` `DeviceData` field when creating the transaction.
