### ISSUE TITLE
Running integration tests ...

### ISSUE THREAD

**Issue by aalpar** [lionelbarrow/braintree-go#77]
Possible dumb question:  How do I create a transaction in the Braintree sandbox with a specific Transaction ID?  I don't see a way through the web-console interface or the API to create a transaction with a specific ID.

**Comment by brmasson** [comment]
The standard SDKs don't allow you to do that AFAIK, so I assume it isn't possible.

**Comment by aalpar** [comment]
The `TESTING.md` file in braintree-go states that I need to create a transaction with the ID `dskdmb`:

```
**Transactions**

The details don't matter, as long as its id is `dskdmb`.
```

What is the process for running the tests without being able to create a transaction with a specific ID?

**Comment by aalpar** [comment]
I found the answer for this: `transaction_integration_test.go` has a disbursement test in it which falls under the guidelines of the comment at the end of the `TESTING.md` file.

Closing issue.
