### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by asib** [lionelbarrow/braintree-go#79]
Hi, I'm looking at using Go to talk to Braintree and found this library. I'm wondering if it's been used in anything serious and whether it will continue to be maintained?

Thanks.

**Comment by HongxingTB** [comment]
We are using this one in production.

**Comment by leighmcculloch** [comment]
@asib: Me and a few other people (see commit history) have been maintaining and continuing to extend the functionality supported by the SDK. If there are features missing you need please open issues or PRs if you'd like to take a stab at it.
