### ISSUE TITLE
Bump api version?

### ISSUE THREAD

**Issue by rkulla** [lionelbarrow/braintree-go#85]
I noticed that the official Ruby sdk is using Api version 4 of braintree, but Braintree-go is still on version 3.

I'm not sure of what the differences are, and 3 still seems to work fine, but it's perhaps worth looking into by someone who knows.

**Comment by leighmcculloch** [comment]
We're actually using ApiVersion4 for some API endpoints where it makes a difference, e.g. [payment_method_gateway.go](https://github.com/lionelbarrow/braintree-go/blob/master/payment_method_gateway.go#L24-L34). I'm guessing we'll probably update the versions of each endpoint to v4 as we need to, to access additional functionality as we make it available in this SDK as was done there.
