### ISSUE TITLE
Forbidden (403) when using nonce token

### ISSUE THREAD

**Issue by bhlvoong** [lionelbarrow/braintree-go#95]
Hello Lionel,

Great work with the library. I'm trying to create a Transaction with the PaymentMethodNonce property instead of using a direct Credit Card payment but keep hitting a 403.  This nonce value is retrieved after my server returns a client token and the client tokenizes their payment through paypal.  Here's roughly how the process looks like:

bt = braintree.New(braintree.Production, merchId, pubKey, privKey)

Client asks for a client token:
token, err := bt.ClientToken().Generate()
//return this token to client

//paypalInstance now uses this token to tokenize a nonce payload and then I send this to my server. I then process this nonce into a Transaction:

nonce := r.URL.Query.get("nonce")
tx, err := bt.Transaction().Create(&braintree.Transaction{
	Type: "sale",
	Amount: amount,
	PaymentMethodNonce: nonce,
	MerchantAccountId: "USD",
})

if err != nil {
	logger.Debugf("Failed to create transaction: %v", err)
	http.Error(w, "", http.StatusInternalServerError)
	return
}

I've checked with braintree and paypal payment method is enabled so I'm not sure if this is the correct implementation for nonce payments.

**Comment by bhlvoong** [comment]
For whatever reason, specify MerchantAccountId: "USD" causes this 403 Forbidden response from Braintree.  I get the same behavior using the Java SDK, so I assume something is incorrectly setup with my account.  Omitting the MerchantAccountId value processes the transactions no problemo.

**Comment by leighmcculloch** [comment]
@bhlvoong: It sounds like the issue was unrelated to this community SDK but rather account setup. I'm going to close this issue. Please reopen if that is not the case.
